# Laboratory of Computational Physics mod. B at Phisics of Data, University of Padova

__Authors:__

- Valeria Fioroni (University of Padova)
- Matteo Guida (University of Padova)
- Philipp Zehetner (University of Padova, Ludwig Maximilian University of Munich)

__Supervised by:__

- Professor Marco Zanetti (University of Padova, CERN)
- Professor Stefano Lacaprara (University of Padova, BELLE2)

## 1. The Signal

At the SuperKEKB paricle accelerator electrons and positrons collide with a center-of-momentum energy clos to the $ \Upsilon (4S) $ resonance. The cross section for the event $ e^+ e^- \rightarrow \Upsilon (4S) $ is 

$$ 
\sigma_{\Upsilon (4S)} = 1.1 \, nb
$$

The $ \Upsilon (4S) $ decays in one of two (almost) equally probable products: 
- $ \Upsilon (4S) \rightarrow B^+ B^- $
- $ \Upsilon (4S) \rightarrow B^0 \bar{B^0} $

For this analysis we are interested in the decay channel
$$
B^0 \rightarrow \eta' \left( \eta \left( \gamma \gamma \right) \pi^+ \pi^- \right) K^0_S \left( \pi^+ \pi^- \right)
$$

The branching fractions are as follows: 

- $ \mathcal{BF} \left( B^0 \rightarrow \eta' K^0 \right) = 6.6 * 10^{-5} $ 
- $ \mathcal{BF} \left( \eta' \rightarrow \eta \pi^+ \pi^- \right) = 0.43 $
- $ \mathcal{BF} \left( \eta \rightarrow \gamma \gamma \right) = 0.40 $
- $ P \left( K^0_S | K^0 \right) = 0.5 $
- $ \mathcal{BF} \left( K^0_S \rightarrow \pi^+ \pi^- \right) = 0.7 $

This leads to a complete branching ratio of 
$ \mathcal{BF} = 3.97 * 10^{-6} $ 

## 2. Our Data

Our Data consists of labelled data, that we used to train and test a _Deep Neural Network_ (DNN) and a _Boosted Decision Tree_ as well as unlabelled data (Data Challenge) in which we are searching for our signal. 

###  Labelled Data

The labelled data consists of various types of background, all corresponding to an integrated luminosity of 
$ \mathcal{L} = 800 \, fb^{-1} $
and signal corresponding to __NSIGNAL__ reconstructed signal events with an efficiency of 
$ \varepsilon = 0.291 $

- $ e^+ e^- \rightarrow u \bar{u} $
- $ e^+ e^- \rightarrow d \bar{d} $
- $ e^+ e^- \rightarrow s \bar{s} $
- $ e^+ e^- \rightarrow c \bar{c} $
- $ e^+ e^- \rightarrow \tau \bar{\tau} $
- $ e^+ e^- \rightarrow B^+ B^- $
- $ e^+ e^- \rightarrow B^0 \bar{B^0} $

We summarize the first five types of backgrounds as _Continuum Background_ and the last two types as _Peaking Background_ and thus build a multi classifier with three types of events. 

Using the complete branching fraction 
$ \mathcal{BF} $
and the cross section 
$ \sigma_{\Upsilon (4S)} $ 
we can calculate to expect to have $N$ events with 
\begin{equation}
N = \mathcal{L} \times \sigma_{\Upsilon(4S)} \times \mathcal{BF} 
= 800 \, fb^{-1} \times 1.1 \, nb \times 3.97 \cdot 10^{-6}
= 3494
\end{equation}
of which $ \varepsilon \times N = 1017 $ should be found by the reconstruction

###  Data Challenge

The Data Challenge is a simulation corresponding to a total luminosity of 
$ \mathcal{L} = 1 \, ab^{-1} $
We can calculate in the same as above, that we should expect a total number of $ N = 4367 $ signal events of which $1271$ are reconstructed. 

In [1]:
import os, sys, pprint
import math
import glob
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import joblib
import warnings
warnings.filterwarnings("ignore")
from root_pandas import read_root
from random import seed
from random import randint
n_seed=1234
seed(n_seed)

Local_Philipp = True
Local_Valeria = False

Welcome to JupyROOT 6.16/00


In [2]:
Training = ['B0_Pcms', 'B0_etap_Pcms', 'B0_etap_eta_Pcms', 'B0_etap_eta_gamma0_Pcms', 'B0_etap_eta_gamma1_Pcms', 'B0_etap_pi0_Pcms', 'B0_etap_pi1_Pcms', 'B0_K_S0_Pcms', 'B0_M', 'B0_ErrM', 'B0_SigM', 'B0_K_S0_M', 'B0_K_S0_ErrM', 'B0_K_S0_SigM', 'B0_etap_M', 'B0_etap_ErrM', 'B0_etap_SigM', 'B0_etap_eta_M', 'B0_etap_eta_ErrM', 'B0_etap_eta_SigM', 'B0_deltae', 'B0_mbc', 'B0_TrCSMVA', 'B0_X', 'B0_ErrX', 'B0_Y', 'B0_ErrY', 'B0_Z', 'B0_ErrZ', 'B0_Rho', 'B0_etap_X', 'B0_etap_ErrX', 'B0_etap_Y', 'B0_etap_ErrY', 'B0_etap_Z', 'B0_etap_ErrZ', 'B0_etap_Rho', 'B0_etap_eta_X', 'B0_etap_eta_ErrX', 'B0_etap_eta_Y', 'B0_etap_eta_ErrY', 'B0_etap_eta_Z', 'B0_etap_eta_ErrZ', 'B0_etap_eta_Rho', 'B0_etap_pi0_X', 'B0_etap_pi0_ErrX', 'B0_etap_pi0_Y', 'B0_etap_pi0_ErrY', 'B0_etap_pi0_Z', 'B0_etap_pi0_ErrZ', 'B0_etap_pi0_Rho', 'B0_etap_pi1_X', 'B0_etap_pi1_ErrX', 'B0_etap_pi1_Y', 'B0_etap_pi1_ErrY', 'B0_etap_pi1_Z', 'B0_etap_pi1_ErrZ', 'B0_etap_pi1_Rho', 'B0_K_S0_X', 'B0_K_S0_ErrX', 'B0_K_S0_Y', 'B0_K_S0_ErrY', 'B0_K_S0_Z', 'B0_K_S0_ErrZ', 'B0_K_S0_Rho', 'B0_cosAngleBetweenMomentumAndVertexVector', 'B0_distance', 'B0_significanceOfDistance', 'B0_dr', 'B0_etap_pi0_dr', 'B0_etap_pi1_dr', 'B0_K_S0_dr', 'B0_decayAngle__bo0__bc', 'B0_decayAngle__bo1__bc', 'B0_etap_decayAngle__bo0__bc', 'B0_etap_decayAngle__bo1__bc', 'B0_etap_decayAngle__bo2__bc', 'B0_VtxPvalue', 'B0_etap_VtxPvalue', 'B0_etap_eta_VtxPvalue', 'B0_etap_pi0_VtxPvalue', 'B0_etap_pi1_VtxPvalue', 'B0_K_S0_VtxPvalue']
Important = Training + ['B0_isSignal', 'evt_no']

if Local_Philipp : 
    path = '/home/philipp/Desktop/Project/DATA/'
    SFiles = glob.glob(os.path.join(path, 'Signal/*.root'))
    CFiles = glob.glob(os.path.join(path, 'Continuous/*.root'))
    PFiles = glob.glob(os.path.join(path, 'Peaking/*.root'))
    DCFiles = glob.glob(os.path.join(path, 'DC/*.root'))
    
if Local_Valeria : 
    path = '/home/utente/Scrivania/Progetto LCP-B/DataBelle2_all/'
    SFiles = glob.glob(os.path.join(path, 'Signal/*.root'))
    CFiles = glob.glob(os.path.join(path, 'Background/Continuum/*.root'))
    PFiles = glob.glob(os.path.join(path, 'Background/Peaking/*.root'))
    DCFiles = glob.glob(os.path.join(path, 'DataChallenge/*.root'))
    
Signal = pd.concat((read_root(f, 'B0', columns=Important) for f in SFiles))
Signal = Signal[Signal['B0_isSignal']==1].reset_index(drop=True)
Continuum_bkg = pd.concat((read_root(f, 'B0', columns=Important) for f in CFiles))
Peaking_bkg = pd.concat((read_root(f, 'B0', columns=Important) for f in PFiles))

#Signal: In case of more than 1 candidate per event select the first one occuring
Mask_duplicated = Signal.duplicated(subset='evt_no', keep='first')
Mask_duplicated=np.logical_not(Mask_duplicated)
Signal=Signal[Mask_duplicated]
Signal.reset_index(drop=True, inplace=True)

Signal=Signal[Training]
Continuum_bkg=Continuum_bkg[Training]
Peaking_bkg=Peaking_bkg[Training]

print("Continuum: {} events".format(Continuum_bkg.shape[0]))
print("Peaking: {} events".format(Peaking_bkg.shape[0]))
print("Signal: {} events \n".format(Signal.shape[0]))
print("Assuming, that originally 1.6M signal events existed, this corresponds to a reconstruction efficiencey of {}%".format(100*Signal.shape[0]/1600000))

Continuum: 246329 events
Peaking: 2167 events
Signal: 218596 events 

Assuming, that originally 1.6M signal events existed, this corresponds to a reconstruction efficiencey of 13.66225%


### Preprocessing our Data

- explain steps in preprocessing

In [3]:
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical

n_classes = 3
Signal['Type'] = 2
Continuum_bkg['Type'] = 1
Peaking_bkg['Type'] = 0

# Splitting Data and Label into train, test and validation separatly for each class
X = Signal.drop('Type',axis=1)
Y = Signal['Type']
X_train_S, X_test_val_S, Y_train_S, Y_test_val_S = train_test_split(X, Y, train_size=0.5,random_state=randint(10**6,10**9))
X = X_test_val_S
Y = Y_test_val_S
X_validation_S, X_test_S, Y_validation_S, Y_test_S = train_test_split(X, Y, train_size=0.6,random_state=randint(10**6,10**9))
del(X_test_val_S)
del(Y_test_val_S)
X = Continuum_bkg.drop('Type',axis=1)
Y = Continuum_bkg['Type']
X_train_C, X_test_val_C, Y_train_C, Y_test_val_C = train_test_split(X, Y, train_size=0.5,random_state=randint(10**6,10**9))
X = X_test_val_C
Y = Y_test_val_C
X_validation_C, X_test_C, Y_validation_C, Y_test_C = train_test_split(X, Y, train_size=0.6,random_state=randint(10**6,10**9))
del(X_test_val_C)
del(Y_test_val_C)
X = Peaking_bkg.drop('Type',axis=1)
Y = Peaking_bkg['Type']
X_train_P, X_test_val_P, Y_train_P, Y_test_val_P = train_test_split(X, Y, train_size=0.5,random_state=randint(10**6,10**9))
X = X_test_val_P
Y = Y_test_val_P
X_validation_P, X_test_P, Y_validation_P, Y_test_P = train_test_split(X, Y, train_size=0.6,random_state=randint(10**6,10**9))
del(X_test_val_P)
del(Y_test_val_P)

# Concatenating the different classes, encoding the label as one-hot vectors and shuffling everything
X_Train=np.concatenate((X_train_S, X_train_C, X_train_P), axis=0)
X_Validation=np.concatenate((X_validation_S, X_validation_C, X_validation_P), axis=0)
X_Test=np.concatenate((X_test_S, X_test_C, X_test_P), axis=0)
Y_Train=np.concatenate((Y_train_S, Y_train_C, Y_train_P), axis=0)
Y_Validation=np.concatenate((Y_validation_S, Y_validation_C, Y_validation_P), axis=0)
Y_Test=np.concatenate((Y_test_S, Y_test_C, Y_test_P), axis=0)
Ỳ_Test_not_encoded=Y_Test #used for cut value analysis
Y_Train=to_categorical(Y_Train, num_classes=3)
Y_Validation=to_categorical(Y_Validation, num_classes=3)
Y_Test=to_categorical(Y_Test, num_classes=3)
permutation = np.random.permutation(X_Train.shape[0])
X_Train = X_Train[permutation]
Y_Train = Y_Train[permutation]
permutation = np.random.permutation(X_Validation.shape[0])
X_Validation = X_Validation[permutation]
Y_Validation = Y_Validation[permutation]
permutation = np.random.permutation(X_Test.shape[0])
X_Test = X_Test[permutation]
Y_Test = Y_Test[permutation]

Using TensorFlow backend.


Write something about the 5 sigma mass cut and why we aren't doing it
It's something we tried, so worth mentioning

Write something about scaling and why it is important

In [23]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
pcTrain = ss.fit_transform(X_Train)
pcTest = ss.transform(X_Test)
pcValidation = ss.transform(X_Validation)

In [5]:
X_Train.shape

(233545, 83)

Write something about PCA, and why we are not doing it

## 3. The Neural Network

explain what neural network we are using, how we have been training it

In [34]:
from keras.models import load_model

Model1 = load_model('Models/LastTry/Best_Model.h5')
Model2 = load_model('Models/LateNight/Best_Model.h5')

print(Model1.summary())
print(Model1.evaluate(pcTest, Y_Test))
print(2*'\n')
print(Model2.summary())
print(Model2.evaluate(pcTest, Y_Test))

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dropout_148 (Dropout)        (None, 83)                0         
_________________________________________________________________
dense_662 (Dense)            (None, 50)                4200      
_________________________________________________________________
dense_663 (Dense)            (None, 100)               5100      
_________________________________________________________________
dense_664 (Dense)            (None, 100)               10100     
_________________________________________________________________
dense_665 (Dense)            (None, 50)                5050      
_________________________________________________________________
dense_666 (Dense)            (None, 3)                 153       
Total params: 24,603
Trainable params: 24,603
Non-trainable params: 0
_________________________________________________________________
None
9

Talk about the performance of our model 

- Model.evaluate with Test sample
- ROCK Curve
- Confusion Matrix

## 4. XGBOOST

- Same story here as in the last chapter
- Advantages/Disadvantages compared to the DNN

## 5. Deciding on the Cut Value of our Network

- all necessary steps and explanations for the cut value

## 6. The Data Challenge

Here we con showcase the perfect performance of our network

In [7]:
DC = pd.concat((read_root(f, 'B0', columns=Training) for f in DCFiles)).reset_index(drop=True)

In [40]:
pcDC = ss.transform(np.array(DC.values))
print(Model1.predict(pcDC))
print('\n', 50*'-', '\n')
print(Model2.predict(pcDC))

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]

 -------------------------------------------------- 

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [41]:
pcDC1 = ss.fit_transform(np.array(DC.values))
print(Model1.predict(pcDC1))
print('\n', 50*'-', '\n')
print(Model2.predict(pcDC1))

[[3.2186895e-03 9.8908037e-01 7.7009602e-03]
 [1.6471164e-02 9.8352885e-01 2.5534923e-09]
 [1.7694786e-02 9.8230529e-01 1.0872415e-09]
 ...
 [3.2141146e-03 1.7170277e-01 8.2508308e-01]
 [4.1421424e-03 2.5818574e-01 7.3767209e-01]
 [5.1302887e-03 8.9486539e-02 9.0538317e-01]]

 -------------------------------------------------- 

[[1.39860185e-02 9.48301852e-01 3.77121717e-02]
 [7.85904005e-03 9.92121935e-01 1.90740229e-05]
 [6.94253435e-03 9.93052006e-01 5.47205127e-06]
 ...
 [9.99862328e-03 5.39819971e-02 9.36019421e-01]
 [1.21847913e-02 7.03602433e-02 9.17454958e-01]
 [3.30546382e-03 1.39677212e-01 8.57017338e-01]]


In [47]:
Signal

B0_Pcms  B0_etap_Pcms  B0_etap_eta_Pcms  B0_etap_eta_gamma0_Pcms  \
0       0.337742      2.715602          1.822239                 1.143091   
1       0.470735      2.385937          1.143156                 0.478281   
2       0.374911      2.376649          1.349594                 0.764921   
3       0.353012      2.354433          1.863505                 1.432046   
4       0.370397      2.731697          1.909907                 1.806603   
5       0.315562      2.607498          1.671275                 0.563308   
6       0.301456      2.668692          1.679291                 1.622698   
7       0.340827      2.411188          1.012029                 0.459017   
8       0.371696      2.587833          1.370511                 0.878335   
9       0.335295      2.669212          1.905520                 0.617216   
10      0.412940      2.708031          1.396734                 0.406750   
11      0.293599      2.537656          1.898875                 1.472718   
12      0.324638      2.547186          1.659195                 0.097729   
13      0.378934      2.368519          1.266528                 0.944661   
14      0.294455      2.600925          1.252519                 1.142190   
15      0.357495      2.429100          1.529960                 0.279519   
16      0.345483      2.575008          1.876526                 1.854825   
17      0.312704      2.543054          1.695796                 1.645686   
18      0.262795      2.589767          1.089616                 0.841992   
19      0.311228      2.386051          0.988045                 0.738253   
20      0.335097      2.644986          1.373010                 0.778539   
21      0.304879      2.547573          1.618955                 1.385901   
22      0.331009      2.520148          1.388111                 1.399758   
23      0.334147      2.689096          1.038900                 0.336645   
24      0.356879      2.620954          1.575537                 0.300304   
25      0.376975      2.709409          2.086431                 1.079195   
26      0.314433      2.590461          1.559475                 1.389817   
27      0.372266      2.720800          1.826491                 0.890959   
28      0.318845      2.661112          1.565112                 0.962365   
29      0.381466      2.333300          1.167949                 0.557265   
...          ...           ...               ...                      ...   
218566  0.320279      2.529121          1.460513                 0.463616   
218567  0.212426      2.546659          0.962334                 0.545623   
218568  0.328433      2.670725          1.043669                 1.055492   
218569  0.450074      2.431354          1.150801                 0.683041   
218570  0.393325      2.658150          1.805747                 0.966159   
218571  0.367453      2.617010          1.189317                 0.476831   
218572  0.318013      2.507913          1.495389                 1.126978   
218573  0.261229      2.640344          1.262999                 0.712628   
218574  0.361087      2.402692          1.755767                 0.819760   
218575  0.327446      2.575117          1.734397                 1.205539   
218576  0.275829      2.453255          1.210386                 0.965543   
218577  0.283538      2.456960          1.868375                 1.487458   
218578  0.328476      2.581831          1.815585                 1.441632   
218579  0.354713      2.641983          1.863682                 0.444854   
218580  0.332073      2.602182          1.454111                 1.032773   
218581  0.484769      2.417097          1.653945                 0.189739   
218582  0.350197      2.480600          1.305203                 0.445378   
218583  0.277961      2.435025          1.617142                 0.324436   
218584  0.354291      2.417787          1.940380                 0.730268   
218585  0.376966      2.383706          1.592316                 1.059833   
21858

In [48]:
DC

B0_K_S0_X  B0_K_S0_Rho  B0_K_S0_Pcms   B0_Pcms  B0_K_S0_SigM  \
0       1.719822     8.064223      2.227635  0.949089      1.211639   
1       5.555710     5.594461      2.539246  0.134671      0.011980   
2       5.555710     5.594461      2.539246  0.141258      0.011980   
3       5.555710     5.594461      2.539246  0.281482      0.011980   
4       5.555710     5.594461      2.539246  0.121087      0.011980   
5       5.555710     5.594461      2.539246  0.211633      0.011980   
6       5.555710     5.594461      2.539246  0.206744      0.011980   
7      -0.207617     0.365994      2.468945  0.865624      0.863792   
8      -0.207617     0.365994      2.468945  0.842772      0.863792   
9      -0.018782     0.020061      2.813157  0.767780     -0.027094   
10     -0.036465     0.044896      2.710775  0.293394     -3.896517   
11      0.039738     0.043286      2.885087  0.906987      3.907134   
12      4.282402     4.941551      2.120332  0.758086     -0.497992   
13      0.435063     0.436406      2.182009  0.914562      3.079941   
14      0.002273     0.008054      2.651295  0.805625     -0.700239   
15      0.002273     0.008054      2.651295  0.853222     -0.700239   
16      0.018166     1.239132      2.655376  0.803733      1.812308   
17      0.018166     1.239132      2.655376  0.851209      1.812308   
18      0.359762     0.463027      2.695340  0.612997     -0.507300   
19     -0.008379     0.021655      2.766026  0.883422      6.360900   
20     -0.008379     0.021655      2.766026  0.806020      6.360900   
21     -0.008379     0.021655      2.766026  0.830002      6.360900   
22      0.046527     0.046528      2.466739  0.681388      1.186259   
23      0.004860     0.015305      2.201935  0.896194     -0.462558   
24      0.004860     0.015305      2.201935  0.777673     -0.462558   
25      0.004860     0.015305      2.201935  0.781431     -0.462558   
26      5.035774     5.967388      2.393738  0.397815      1.091824   
27      0.004722     0.009226      2.761801  0.824058      7.626786   
28      0.004722     0.009226      2.761801  0.855804      7.626786   
29      0.004722     0.009226      2.761801  0.848063      7.626786   
...          ...          ...           ...       ...           ...   
98717  -0.895136     1.050609      2.612397  0.597526     -0.904619   
98718  -0.055903     0.064441      2.894911  0.778643     -5.227191   
98719  -0.055903     0.064441      2.894911  0.814229     -5.227191   
98720  -0.055903     0.064441      2.894911  0.641339     -5.227191   
98721  -0.055903     0.064441      2.894911  0.609267     -5.227191   
98722  -0.164929     0.165842      2.562625  0.060798     -4.375618   
98723  -0.164929     0.165842      2.562625  0.142191     -4.375618   
98724  -0.555906     0.757475      2.520158  0.513906      5.171293   
98725   4.726124     4.818212      2.475030  0.344012      1.061194   
98726  -0.052468     0.065078      2.403683  0.311458     -2.508575   
98727  -0.052468     0.065078      2.403683  0.364265     -2.508575   
98728   0.074002     0.271641      2.457520  0.530927      3.822718   
98729   0.074002     0.271641      2.457520  0.522810      3.822718   
98730   0.074002     0.271641      2.457520  0.537753      3.822718   
98731   0.074002     0.271641      2.457520  0.503655      3.822718   
98732   0.011938     0.013614      2.627244  0.383688     -1.851356   
98733  -1.728383     1.729236      2.627602  0.866867     -0.374077   
98734  -0.003623     0.003641      2.319596  0.795353      2.027671   
98735   0.061606     0.633539      2.278224  0.807376     -1.004328   
98736  -0.026162     0.032351      2.312084  0.929857     -6.588702   
98737  -0.026162     0.032351      2.312084  0.920001     -6.588702   
98738  -0.026162     0.032351      2.312084  0.883323     -6.588702   
98739   0.405702     0.904487      2.542627  0.702886     -3.003659   
98740   0.002296     0.003275      2.728925  0.917195     12.545298   
98741   0.002296     0.003275  

In [46]:
print(DC.columns)
print('\n', 50*'-', '\n')
print(Signal.columns)

Index(['B0_K_S0_X', 'B0_K_S0_Rho', 'B0_K_S0_Pcms', 'B0_Pcms', 'B0_K_S0_SigM',
       'B0_etap_pi1_Rho', 'B0_SigM', 'B0_etap_Z', 'B0_etap_pi1_X',
       'B0_K_S0_VtxPvalue', 'B0_Z', 'B0_etap_ErrZ', 'B0_K_S0_ErrX',
       'B0_K_S0_ErrY', 'B0_etap_pi0_dr', 'B0_etap_pi1_Z',
       'B0_decayAngle__bo0__bc', 'B0_K_S0_ErrZ', 'B0_etap_pi1_ErrY',
       'B0_etap_eta_Pcms', 'B0_distance', 'B0_etap_eta_ErrY', 'B0_etap_eta_Z',
       'B0_etap_pi1_Pcms', 'B0_etap_Rho', 'B0_etap_pi1_ErrZ',
       'B0_etap_pi1_ErrX', 'B0_etap_eta_Y', 'B0_M', 'B0_etap_M', 'B0_K_S0_dr',
       'B0_etap_pi0_ErrX', 'B0_X', 'B0_etap_Pcms', 'B0_etap_eta_gamma0_Pcms',
       'B0_etap_ErrX', 'B0_etap_eta_X', 'B0_etap_pi0_Pcms',
       'B0_decayAngle__bo1__bc', 'B0_etap_pi0_VtxPvalue', 'B0_ErrZ',
       'B0_K_S0_M', 'B0_etap_eta_Rho', 'B0_K_S0_Y', 'B0_TrCSMVA',
       'B0_etap_pi1_Y', 'B0_etap_pi1_dr', 'B0_etap_eta_ErrX', 'B0_Y',
       'B0_etap_decayAngle__bo0__bc', 'B0_etap_pi0_ErrY', 'B0_etap_eta_M',
       'B0_etap_VtxPva

## 7. Conclusion or additional comments (optional)

If you think somthing is missing feel free to add it. 
With 6 topics we can give 2 (non consecutive) topics for everybody. 
Having a little break between your two topics maybe helps a bit if something didn't go as expected. 